Controllers/BillingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using OfficeOpenXml;
using System;
using System.Data;
using System.IO;

namespace BoschACDC.Controllers
{
    public class BillingController : Controller
    {
        private readonly IConfiguration config;

        public BillingController(IConfiguration _config)
        {
            config = _config;
        }
        public IActionResult Index()
        {
            return View();
        }

        private DataSet GetDataReimbursement(string startDate, string stopDate, string storedName)
        {
            DataSet dsResult = new DataSet();

            try
            {
                string strConnection = config.GetValue<string>("ConnectionStrings:SysFreight");
                using (SqlDataAdapter myDataAdapter = new SqlDataAdapter(storedName, strConnection))
                {
                    myDataAdapter.SelectCommand.CommandType = CommandType.StoredProcedure;
                    myDataAdapter.SelectCommand.Parameters.Add("@StartDate", SqlDbType.VarChar).Value = startDate;
                    myDataAdapter.SelectCommand.Parameters.Add("@EndDate", SqlDbType.VarChar).Value = stopDate;
                    myDataAdapter.Fill(dsResult);
                }
                return dsResult;
            }
            catch (Exception ex)
            {
                throw new Exception(ex.ToString());
            }
        }

        private MemoryStream CreateExcelFile(DataSet dsResult)
        {
            try
            {
                DataTable dtSheet1 = dsResult.Tables[0];
                DataTable dtSheet2 = dsResult.Tables[1];

                string strTemplateReimbursement = config.GetValue<string>("AppSettings:PathTemplateReimbursement");

                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                MemoryStream stream = new MemoryStream();

                using (var package = new ExcelPackage(strTemplateReimbursement))
                {
                    var sheet = package.Workbook.Worksheets["Import_template"];
                    Int16 intRow = 11;

                    foreach (DataRow drRow in dtSheet1.Rows)
                    {
                        sheet.Cells[$"A{intRow.ToString()}"].Value = drRow["Row#"];
                        sheet.Cells[$"B{intRow.ToString()}"].Value = drRow["Entity_LSP_Billing_period"].ToString().Trim();
                        sheet.Cells[$"C{intRow.ToString()}"].Value = drRow["InvoiceDate"].ToString().Trim();
                        sheet.Cells[$"D{intRow.ToString()}"].Value = drRow["AwbOrBlNo"].ToString().Trim();
                        sheet.Cells[$"E{intRow.ToString()}"].Value = drRow["JobNo"].ToString().Trim();
                        sheet.Cells[$"F{intRow.ToString()}"].Value = drRow["Etd"].ToString().Trim();
                        sheet.Cells[$"G{intRow.ToString()}"].Value = drRow["Eta"].ToString().Trim();
                        sheet.Cells[$"H{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"I{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"J{intRow.ToString()}"].Value = drRow["ServiceType"].ToString().Trim();
                        sheet.Cells[$"K{intRow.ToString()}"].Value = drRow["Cost_type"].ToString().Trim();
                        sheet.Cells[$"L{intRow.ToString()}"].Value = drRow["Business_Case"].ToString().Trim();
                        sheet.Cells[$"M{intRow.ToString()}"].Value = drRow["Freight_Mode"].ToString().Trim();
                        sheet.Cells[$"N{intRow.ToString()}"].Value = drRow["Transport_Mode"].ToString().Trim();
                        sheet.Cells[$"O{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"P{intRow.ToString()}"].Value = drRow["ShipperName"].ToString().Trim();
                        sheet.Cells[$"Q{intRow.ToString()}"].Value = drRow["OriginName"].ToString().Trim();
                        sheet.Cells[$"R{intRow.ToString()}"].Value = drRow["CountryOfOrigin"].ToString().Trim();
                        sheet.Cells[$"S{intRow.ToString()}"].Value = drRow["Origin_postal_code"].ToString().Trim();
                        sheet.Cells[$"T{intRow.ToString()}"].Value = drRow["Port_of_departure"].ToString().Trim();
                        sheet.Cells[$"U{intRow.ToString()}"].Value = drRow["ConsigneeName"].ToString().Trim();
                        sheet.Cells[$"V{intRow.ToString()}"].Value = drRow["Destination_City"].ToString().Trim();
                        sheet.Cells[$"W{intRow.ToString()}"].Value = drRow["Destination_Country"].ToString().Trim();
                        sheet.Cells[$"X{intRow.ToString()}"].Value = drRow["Destination_postal_code"].ToString().Trim();
                        sheet.Cells[$"Y{intRow.ToString()}"].Value = drRow["DestCode"].ToString().Trim();
                        sheet.Cells[$"Z{intRow.ToString()}"].Value = drRow["DeliveryType"].ToString().Trim();
                        sheet.Cells[$"AA{intRow.ToString()}"].Value = drRow["NumberofContainer"];
                        sheet.Cells[$"AB{intRow.ToString()}"].Value = drRow["GrossWeight"];
                        sheet.Cells[$"AC{intRow.ToString()}"].Value = drRow["ChargeWeight"];
                        sheet.Cells[$"AD{intRow.ToString()}"].Value = drRow["Volume"];
                        sheet.Cells[$"AE{intRow.ToString()}"].Value = drRow["LocalAmt"];
                        sheet.Cells[$"AF{intRow.ToString()}"].Value = drRow["VatAmt"];
                        sheet.Cells[$"AG{intRow.ToString()}"].Value = drRow["Remark_position"];
                        sheet.Cells[$"AH{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AI{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AJ{intRow.ToString()}"].Value = drRow["InvoiceLocalAmt"];
                        sheet.Cells[$"AK{intRow.ToString()}"].Value = drRow["TotalVatAmt"];
                        sheet.Cells[$"AL{intRow.ToString()}"].Value = drRow["InvoiceAndVatLocalAmt"];
                        sheet.Cells[$"AM{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AN{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AO{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AP{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AQ{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AR{intRow.ToString()}"].Value = drRow["CommercialInvoiceNo"].ToString().Trim();
                        sheet.Cells[$"AS{intRow.ToString()}"].Value = drRow["R_contorl"].ToString().Trim();
                        sheet.Cells[$"AT{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AU{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AV{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AW{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AX{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AY{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"AZ{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"BA{intRow.ToString()}"].Value = drRow["Container_type"].ToString().Trim();
                        sheet.Cells[$"BB{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"BC{intRow.ToString()}"].Value = string.Empty;
                        sheet.Cells[$"BD{intRow.ToString()}"].Value = drRow["DecNo"].ToString().Trim();
                        ++intRow;
                    }

                    intRow = 3;
                    var sheet2 = package.Workbook.Worksheets["Reimbursement_MOL"];
                    foreach (DataRow drRow in dtSheet2.Rows)
                    {
                        sheet2.Cells[$"D{intRow.ToString()}"].Value = drRow["LocalAmt"];
                        sheet2.Cells[$"E{intRow.ToString()}"].Value = drRow["Description"].ToString().Trim();
                        sheet2.Cells[$"F{intRow.ToString()}"].Value = drRow["Business_Case"].ToString().Trim();
                        sheet2.Cells[$"G{intRow.ToString()}"].Value = drRow["Trasport_Mode"].ToString().Trim();
                        sheet2.Cells[$"H{intRow.ToString()}"].Value = drRow["AwbOrBlNo"].ToString().Trim();
                        sheet2.Cells[$"I{intRow.ToString()}"].Value = drRow["Remark_position"].ToString().Trim();
                        ++intRow;
                    }

                    package.SaveAs(stream);
                    stream.Position = 0;
                }
                //using (var package = new ExcelPackage(strTemplateReimbursement))
                //{
                //    var sheet = package.Workbook.Worksheets["Import_template"];
                //    Int16 intRow = 11;

                //    foreach (DataRow drRow in dtSheet1.Rows)
                //    {
                //        sheet.Cells[$"A{intRow.ToString()}"].Value = drRow["Row#"];
                //        sheet.Cells[$"B{intRow.ToString()}"].Value = drRow["Entity_LSP_Billing_period"].ToString().Trim();
                //        sheet.Cells[$"C{intRow.ToString()}"].Value = drRow["InvoiceDate"].ToString().Trim();
                //        sheet.Cells[$"D{intRow.ToString()}"].Value = drRow["AwbOrBlNo"].ToString().Trim();
                //        sheet.Cells[$"E{intRow.ToString()}"].Value = drRow["Etd"].ToString().Trim();
                //        sheet.Cells[$"F{intRow.ToString()}"].Value = drRow["ServiceType"].ToString().Trim();
                //        sheet.Cells[$"G{intRow.ToString()}"].Value = drRow["Cost_type"].ToString().Trim();
                //        sheet.Cells[$"H{intRow.ToString()}"].Value = drRow["Business_Case"].ToString().Trim();

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoschACDC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="asset/plugin/sweetalert/css/sweetalert2.css" rel="stylesheet">
    <link href="~/css/toastr.min.css" rel="stylesheet" />
    <link href="~/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BoschACDC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Update BU</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Home" asp-action="UpdateBU">Update BU by Manual</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Home" asp-action="UploadExcelFile">Update BU by Excel file</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Billing" asp-action="Index">Billing</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BoschACDC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>